# Generated by Django 4.2.1 on 2023-05-11 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_id_alter_activity_id_alter_business_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryItem',
            new_name='Item',
        ),
    ]
