# Generated by Django 4.2.1 on 2023-05-13 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_account_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.JSONField()),
                ('tax', models.DecimalField(decimal_places=2, max_digits=4)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.business')),
            ],
        ),
    ]
